version: "3.8"

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      json-server:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://rabbitmq

  json-server:
    build:
      context: ./data
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  rabbitmq:
    image: "rabbitmq:management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "secretcookie"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672" # Server
      - "15672:15672" # Management
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  rabbitmq_data:
