FROM node:21

# Install dependencies
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy wait-for-it
COPY wait-for-it.sh /usr/wait-for-it.sh
RUN chmod +x /usr/wait-for-it.sh

# Install any needed packages specified in package.json
COPY package*.json ./
RUN npm install

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Make port 3001 available to the world outside this container
EXPOSE 3001

# Define environment variable
ENV NODE_ENV production

# Run server.js when the container launches
CMD ["/usr/wait-for-it.sh", "rabbitmq:5672", "--", "node", "server.js"]
